# configs/dataset_configs/natural_questions_config.yaml
name: "natural_questions"
data_path: "data/natural_questions"
preprocessing:
  max_seq_length: 384
  doc_stride: 128
  max_query_length: 64
  max_answer_length: 30
  train_file: "train.jsonl"
  dev_file: "dev.jsonl"
augmentation:
  enabled: false
  techniques: []