# configs/dataset_configs/natural_questions_config.yaml
dataset:
  name: "natural_questions"
  version: "0.0.2"
  preprocessing:
    max_seq_length: 512
    doc_stride: 128
    max_query_length: 64
    pad_to_max_length: true
    truncation: true
    return_overflowing_tokens: true
    return_offsets_mapping: true
  data_loader:
    train_batch_size: 12
    eval_batch_size: 24
    num_workers: 4
    pin_memory: true