# configs/dataset_configs/squad_config.yaml
name: "squad"
data_path: "data/squad"
version: "2.0"
preprocessing:
  max_seq_length: 384
  doc_stride: 128
  max_query_length: 64
  max_answer_length: 30
  train_file: "train-v2.0.json"
  dev_file: "dev-v2.0.json"
augmentation:
  enabled: false
  techniques: []