# SQuAD dataset configuration
name: "squad"
data_path: "data/squad"
train_file: "train-v1.1.json"
dev_file: "dev-v1.1.json"

# Data processing settings
max_seq_length: 384
doc_stride: 128
max_query_length: 64
max_answer_length: 30

# Other dataset-specific settings
version: "1.1"
preprocessing:
  lowercase: true
  remove_html: true
  remove_special_chars: false